wheel_radius: 0.06
wheel_width: 0.04
wheel_base: 0.28
wheel_tread: 0.28
vehicle_mass: 5000.0
vehicle_length: 0.42
vehicle_width: 0.42
vehicle_height: 0.75
minimum_turning_radius: 0.5
maximum_steering_angle: 97.3 #deg